import { Bombe } from "./Bombe";

test("should find crib match", () => {
  // "IBELIEVETHATATTHEENDOFTHECENTURYTHEUSEOFWORDSANDGENERALEDUCATEDOPINIONWILLHAVEALTEREDSOMUCHTHATONEWILLBEABLETOSPEAKOFMACHINESTHINKINGWITHOUTEXPECTINGTOBECONTRADICTED",
  // "HJCDDNSYHNKEBAUGTZYGLCEVCMXFPCCESSZXEQDHEFIUZNEOIVGHKQBXXPWCJMJZMQBQAYPDPRGFXXDIOBBGUERHJFTHIWUXMAOUXXUOFKFKXPBZYFCELCQAZGPKKLEHXUOMHVJGVRKMYYLUEAJBQMANJMJQUVYJSBZZU";
  const bombe = new Bombe(
    "HJCDDNSYHNKEBAUGTZYGLCEVCMXFPCCESSZXEQDHEFIUZNEOIVGHKQBXXPWCJMJZMQBQAYPDPRGFXXDIOBBGUERHJFTHIWUXMAOUXXUOFKFKXPBZYFCELCQAZGPKKLEHXUOMHVJGVRKMYYLUEAJBQMANJMJQUVYJSBZZU",
    "MACHINESTHINKING"
  );
  expect(bombe.findCribMatches()).toEqual("CQAZGPKKLEHXUOMH");
});

test("should find crib match", () => {
  // "IBELIEVETHATATTHEENDOFTHECENTURYTHEUSEOFWORDSANDGENERALEDUCATEDOPINIONWILLHAVEALTEREDSOMUCHTHATONEWILLBEABLETOSPEAKOFMACHINESTHINKINGWITHOUTEXPECTINGTOBECONTRADICTED",
  // "HJCDDNSYHNKEBAUGTZYGLCEVCMXFPCCESSZXEQDHEFIUZNEOIVGHKQBXXPWCJMJZMQBQAYPDPRGFXXDIOBBGUERHJFTHIWUXMAOUXXUOFKFKXPBZYFCELCQAZGPKKLEHXUOMHVJGVRKMYYLUEAJBQMANJMJQUVYJSBZZU";
  const bombe = new Bombe(
    "HJCDDNSYHNKEBAUGTZYGLCEVCMXFPCCESSZXEQDHEFIUZNEOIVGHKQBXXPWCJMJZMQBQAYPDPRGFXXDIOBBGUERHJFTHIWUXMAOUXXUOFKFKXPBZYFCELCQAZGPKKLEHXUOMHVJGVRKMYYLUEAJBQMANJMJQUVYJSBZZU",
    "EDUCATEDOPINIONWILLHAVEALTEREDSOMUCHTHATONEWILLBEABLETOSPEAKOFMACHINE"
  );
  expect(bombe.findCribMatches()).toEqual([
    "XXPWCJMJZMQBQAYPDPRGFXXDIOBBGUERHJFTHIWUXMAOUXXUOFKFKXPBZYFCELCQAZGPK",
  ]);
});
